## Milestone 3 OV7670 camera constraints.
##
## Physical module verified from front/back photographs:
##   unbranded 18-pin, no-FIFO OV7670 breakout
##   front labels: 3.3V/DGND, SCL/SDA, VS/HS, PLK/XLK,
##                 D7/D6, D5/D4, D3/D2, D1/D0, RET/PWDN
##
## Camera data uses high-speed Pmod JC. Timing and control use high-speed
## Pmod JB. PCLK uses clock-capable pin JB1.

## Camera outputs to FPGA.
set_property -dict { PACKAGE_PIN E15 IOSTANDARD LVCMOS33 } [get_ports cam_pclk]       ; # JB1  <- PLK
set_property -dict { PACKAGE_PIN E16 IOSTANDARD LVCMOS33 } [get_ports cam_vsync]      ; # JB2  <- VS
set_property -dict { PACKAGE_PIN D15 IOSTANDARD LVCMOS33 } [get_ports cam_href]       ; # JB3  <- HS
set_property -dict { PACKAGE_PIN U12 IOSTANDARD LVCMOS33 } [get_ports {cam_d[0]}]     ; # JC1  <- D0
set_property -dict { PACKAGE_PIN V12 IOSTANDARD LVCMOS33 } [get_ports {cam_d[1]}]     ; # JC2  <- D1
set_property -dict { PACKAGE_PIN V10 IOSTANDARD LVCMOS33 } [get_ports {cam_d[2]}]     ; # JC3  <- D2
set_property -dict { PACKAGE_PIN V11 IOSTANDARD LVCMOS33 } [get_ports {cam_d[3]}]     ; # JC4  <- D3
set_property -dict { PACKAGE_PIN U14 IOSTANDARD LVCMOS33 } [get_ports {cam_d[4]}]     ; # JC7  <- D4
set_property -dict { PACKAGE_PIN V14 IOSTANDARD LVCMOS33 } [get_ports {cam_d[5]}]     ; # JC8  <- D5
set_property -dict { PACKAGE_PIN T13 IOSTANDARD LVCMOS33 } [get_ports {cam_d[6]}]     ; # JC9  <- D6
set_property -dict { PACKAGE_PIN U13 IOSTANDARD LVCMOS33 } [get_ports {cam_d[7]}]     ; # JC10 <- D7

## FPGA outputs to camera. Low drive strength limits unnecessary edge current.
set_property -dict { PACKAGE_PIN C15 IOSTANDARD LVCMOS33 DRIVE 4 SLEW FAST } [get_ports cam_xclk]    ; # JB4  -> XLK
set_property -dict { PACKAGE_PIN K15 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW } [get_ports cam_reset_n] ; # JB9  -> RET
set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW } [get_ports cam_pwdn]    ; # JB10 -> PWDN
set_property -dict { PACKAGE_PIN J17 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW } [get_ports cam_sio_c]   ; # JB7  -> SCL

## SDA is open-drain in RTL. This weak FPGA pull-up matches the photographed
## module's direct SCCB connection without adding another actively driven high.
set_property -dict { PACKAGE_PIN J18 IOSTANDARD LVCMOS33 DRIVE 4 PULLUP TRUE } [get_ports cam_sio_d] ; # JB8 <-> SDA

## The design configures a nominal 24 MHz camera clock. PCLK is generated by
## the camera and is asynchronous to the board's 100 MHz system clock.
create_clock -name cam_pclk -period 41.667 -waveform {0.000 20.833} [get_ports cam_pclk]
set_clock_groups -asynchronous -group [get_clocks sys_clk_pin] -group [get_clocks cam_pclk]

## reset_sync asserts these preset pins asynchronously by design. Reset release
## is made safe by the two 24 MHz synchronizer stages, so recovery/removal from
## the 100 MHz reset source to these asynchronous preset pins is not timed.
set_false_path -to [get_pins {
    u_camera_clock/u_xclk_reset/reset_ff1_reg/PRE
    u_camera_clock/u_xclk_reset/reset_ff2_reg/PRE
    u_camera_reset/reset_ff1_reg/PRE
    u_camera_reset/reset_ff2_reg/PRE
}]

## Final source-synchronous input delays require a measured PCLK and wiring
## skew. Do not add guessed values merely to silence timing warnings.
